worker_processes 1;

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;
  server {
    listen 8080;
    location / {
      proxy_pass http://frontend;
    }
    location /api/ {
      proxy_pass http://backend:8000/;
      proxy_set_header Host $host;
    }
  }
}
